### ISSUE TITLE
关于假人动作

### ISSUE THREAD

**Issue by RedstoneRepeater** [fcsailboat/Carpet-Org-Addition#34]
希望org什么时候能够添加一个carpet选项，可以选择org的假人动作指令是使用默认的/playerAction还是使用/player前缀

**Comment by fcsailboat** [comment]
暂时不会考虑这样做，原因如下：
1. 由于原版命令系统本身的限制，所以不方便（不是说不能做）制作开关。
2. 玩家们已经习惯了/playerAction命令，如果取消/playerAction，直接合并到/player命令，那么该如何通知玩家我们做了这项更改？
3. B站的一些视频教程中，演示的都是/playerAction，如果我改了，那些视频教程都会成为过时教程。
4. 在我认识的一些服务器中，有些使用了告示牌命令模组，可以通过右击告示牌执行命令，如果这条命令被更改了，那他们的告示牌命令也要跟着修改。
